### ISSUE TITLE
Crash when collecting items dropped on death with a full pot equipped

### ISSUE THREAD

**Issue by snoevillagercraft** [BeansGalaxy/BeansBackpacks#3]
Basically, when you equip a full pot (2000 items) and die, when picking up the dropped items the game crash

screenshot 2023-12-07: (https://github.com/BeansGalaxy/BeansBackpacks/assets/153205447/edec831e-9e33-488c-bc98-7957e0ca1bf2)

FULL CRASH LOG
[crash-2023-12-07_11.20.35-server.txt](https://github.com/BeansGalaxy/BeansBackpacks/files/13601980/crash-2023-12-07_11.20.35-server.txt)

**Comment by BeansGalaxy** [comment]
I figured I'd let players hold as many items as they want but I didn't think anyone would really do it...
The crash should be fixed in v1.1.1
