### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by ghost** [BeansGalaxy/BeansBackpacks#4]
I download the mod to the server but I get this error and the server is shutting down

![image](https://github.com/BeansGalaxy/BeansBackpacks/assets/150679276/ce646ef9-5d34-4427-be86-a6d2339418b0)

**Comment by BeansGalaxy** [comment]
Fixed the issue in v1.2.0. Thanks for trying out my mod on a server. :)

https://modrinth.com/mod/beans-backpacks/version/1.2.0-1.20.2
