### ISSUE TITLE
When I open the bag the server shuts down.

### ISSUE THREAD

**Issue by ghost** [BeansGalaxy/BeansBackpacks#5]
First of all, thank you for taking my problem into consideration and solving it. However when I install the v1.2.0 version of the mod on the server and put the backpack on ground, the server shuts down. (similiarly, when i put the backpack into a cauldron for remove the color of backpack, the server shuts down)

The error we get from the server when we put the backpack on the ground:
![image](https://github.com/BeansGalaxy/BeansBackpacks/assets/150679276/ecfca04f-a02a-456a-aee0-fac41db23c9f)

**Comment by BeansGalaxy** [comment]
When making this mod I only tested the Multiplayer on a Lan server, not an actual server. Working on a fix but, it might take some time considering most of the Multiplayer stuff was technically never tested.

**Comment by BeansGalaxy** [comment]
v1.2.1 has fixed the issues you said, and I tested most the features in a real server to make sure they are actually working. Btw don't be confused when you can't remove the color from a Backpack by using a cauldron, placing the backpack was crashing the game and you were placing the backpack onto the cauldron.
