### ISSUE TITLE
Please add 1.20.1 Support!

### ISSUE THREAD

**Issue by RudeCanine** [BeansGalaxy/BeansBackpacks#6]
There's no good backpack mod that works with 1.20.1, and I want to use yours!

**Comment by BeansGalaxy** [comment]
I'm currently re-writing the mod so that you can play on forge and add your own backpacks using Json. I don't really know how to backport, and I don't know where to start. So once the re-write's finished, backporting will be the first priority. Glad to see you're excited though!

**Comment by BeansGalaxy** [comment]
btw I added 1.20.1 support. :)
