### ISSUE TITLE
Cannot read field "field_7498" because "player" is null 1.20.1 / 0.1.0b

### ISSUE THREAD

**Issue by ReazonIAm** [BeansGalaxy/BeansBackpacks#9]
This error occurs every time a player dies and presses "Respawn".
Doesn't matter, if backpack equipped or not.
Running on dedicated server with friends, kicks all active sessions with error "Cannot read field "field_7498" because "player" is null"

Server exception:
```
[21:49:36] [Netty Server IO #20/ERROR]: Exception occurred in netty pipeline
java.lang.NullPointerException: Cannot read field "field_7498" because "player" is null
        at com.beansgalaxy.beansbackpacks.screen.BackSlot.get(BackSlot.java:53) ~[beansbackpacks-0.1.0-1.20.1.jar:?]
        at com.beansgalaxy.beansbackpacks.networking.packages.sSyncBackSlot.callSyncBackSlot(sSyncBackSlot.java:41) ~[beansbackpacks-0.1.0-1.20.1.jar:?]
```
(all the other stacktrace is just fabric network api gibberish)

I think the error occures when player entity (object) is deleted and mod tries to access the backpack slot (object property) for whatever reason.
Although, this is 0.1.0 beta, I see this is a backport of current release version and the problem might be actual on 1.20.2 as well.
I can do aditional testing on the version if needed.

> The mod is so impressive for me, that the error isn't really an issue for me. I absolutely love every little detail, that went into this mod, from backpack entity physics to interractions.
I'm here just to provide as much feedback as needed.

**Comment by BeansGalaxy** [comment]
Super simple mistake, super simple fix. v0.1.1 fixes the crash you're having.

P.S. 
Big thank you! I put a lot of thought into each mechanic and I'm glad you appreciate each of them. I wanted the backpack to seem a lot like a block since I made this because nyf's backpacks kept crashing my world and that was how they did it. Funny that now I'm crashing your worlds! :)

**Comment by ReazonIAm** [comment]
I don't really have any of your socials to hit you with the question, so I'll use my closed issue as an opportunity, hit me with more appropriate version if needed :)

I noticed backpack's unusual behaviour with single item stacks. I have 9 mending books in the backpack and it's the maximum I can add to it, which seems a bit strange.

![image](https://github.com/BeansGalaxy/BeansBackpacks/assets/43770747/be30be64-63aa-45ee-89b1-f796ed460d0a)

Removing one book and adding a bunch of other items to the backpack reveals that i can add 64 more different items.

![image](https://github.com/BeansGalaxy/BeansBackpacks/assets/43770747/55ee8ab9-5d86-4628-8d18-29c0ec81e053)

As the capacity of the golden backpack is 9 stacks, this implies, that having 1 item, which is considered non-stackable counts as 1 whole stack of items. This is intended behaviour of a bundle, AFAIK, but seems a bit less appropriate/desirable for the backpack. 

Is this behaviour intended? If not, do you consider changing to to handling non-stackable items to count as 1 item or 1/4 of a stack (similar to 16 items) to the overall capacity?

I'd love for the backpack to break the flow of "1 slot == 1 item" because it would add one more usefult and distinct feature to it without adding more overall capacity to it. 
If it's not in your vision, but fairly simple to implement, could it become a togglable option in the config?
Is it a reasonable idea for me to dig into java and modding framework to make a pull request (as the functional suggestions)?
Of course, following project structure and code practices.
